; CoolQ Assembly SDK
; MIT License
; Copyright (c) 2020 frc
; Email: frc@xiaorou.net.cn
; Email: frc@gmail.com
; QQ: 2093003592
; Documentation: https://github.com/frc123/CoolQ-Assembly-SDK/wiki

include		windows.inc
include		user32.inc
includelib	user32.lib
include		kernel32.inc
includelib	kernel32.lib
include		crypt32.inc
includelib	crypt32.lib
;↑↑↑↑↑↑↑↑↑↑ DO NOT REMOVE ↑↑↑↑↑↑↑↑↑↑
;↓↓↓↓↓ include header/lib hear ↓↓↓↓↓


